name: Workbooks CICD

on:
  push:
    branches: [ main ]
    paths: templates/**
    
  workflow_dispatch:
  
env:
  resourceGroup: monitorrg

jobs:
  validation:
    name: Validations
    runs-on: ubuntu-latest
    
    steps:        
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}           
        
      - name: Validate ARM Template
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
          resourceGroupName: ${{ env.resourceGroup }}
          template: azuredeploy.json
          deploymentMode: Validate          

      - name: Upload Template as Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: StorageTemplate
          # A file, directory or wildcard pattern that describes what to upload
          path: ./templates/sample.json
          if-no-files-found: error

  PROD:
    name: Deploy to PROD
    if: github.event.ref == 'refs/heads/main'
    needs: [validation]
    runs-on: ubuntu-latest
      
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.8
        with:
          name: StorageTemplate         
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy ARM Template
        id: deployArmProd
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.SUBSCRIPTIONID }}          
          resourceGroupName: ${{ env.resourceGroup }}
          template: sample.json
          deploymentMode: Incremental
